# Generated by Django 4.1.7 on 2023-02-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=10)),
                ('position', models.PositiveIntegerField()),
                ('ref_allele', models.CharField(max_length=100)),
                ('alt_allele', models.CharField(max_length=100)),
                ('quality', models.FloatField()),
                ('info', models.TextField()),
            ],
        ),
    ]
